### ISSUE TITLE
Invite party ?

### ISSUE THREAD

**Issue by magaspar** [iXyles/fortnite-basic-api#17]
Hi ! First thanks for your job !
I was wondering if the implementation for inviting a friend into a party was done ?
I can't find it in the documentation (if it's here my bad).
If it's not i'm probably gonna do my own function, tell me if you'r already working on it or if i can do a PR once i'm done :)
Have a great day !

**Comment by iXyles** [comment]
Hello,
No this library does not support party things and have not had any plans to do it either due to the amount of work/changes it is each time they do a modification to it. There is another library which has basic party functionality already in JS. Otherwise a friend of mine "Terbau" got a library in Python for this.

I have no plans to add support for this, so if you wish to create your custom version of the library you're free to do so. But it'll probably not be merging it in, due to the amount of work to maintain it.
