### ISSUE TITLE
Cannot login

### ISSUE THREAD

**Issue by PomegranateApps** [iXyles/fortnite-basic-api#36]
I'm receiving this message when I try to login.

`[getOAuthToken] Cannot proceed login because CAPTCHA rate limit: talon`

**Comment by PomegranateApps** [comment]
Can you help me understand why I am getting this error?

**Comment by iXyles** [comment]
The issue is coming from Epic because they have enforced CAPTCHA on all login requests. The regular login auth with email & password is not a good way to do it anymore. And no sorry I do not have a good workaround for this, it is better to look for other ways to authenticate or just make it possible to pass in a valid exchange code to generate the device tokens as described in one of the samples.

**Comment by PomegranateApps** [comment]
Ok, thanks for letting me know! What are others doing like Fortnite Tracker to circumvent this?

**Comment by iXyles** [comment]
They have generated "device tokens" which can be done with the lib, if you supply an exchange code manually instead of using the "login" sequence

**Comment by PomegranateApps** [comment]
How do you get the exchange code? I tried the instructions in the Readme but the link gives me this error.

`Cannot GET /id/api/exchange`

**Comment by PomegranateApps** [comment]
Ok, I was able to get the exchange code and generate the device auths. How do I get the access token?

**Comment by edsson-madrigal** [comment]
> Ok, I was able to get the exchange code and generate the device auths. How do I get the access token?

How did you get the exchange code? im getting Cannot GET /id/api/exchange

thank you
